# Generated by Django 3.1.4 on 2021-01-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listingID',
            new_name='listingId',
        ),
    ]
