# Generated by Django 3.1.4 on 2021-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_currbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currBid',
        ),
        migrations.AddField(
            model_name='listing',
            name='highestBid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
