# Generated by Django 3.1.4 on 2021-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210107_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='highestBid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
